### ISSUE TITLE
No handlers could be found for logger "fuse"

### ISSUE THREAD

**Issue by noahc3** [jakibaki/switch-usb-mounter#4]
```
F:\SwitchHacking\switch-usb-mounter>mount.py V
No handlers could be found for logger "fuse"
The service python has failed to start (Status=c000000d).
Traceback (most recent call last):
  File "F:\SwitchHacking\switch-usb-mounter\mount.py", line 163, in <module>
    main(sys.argv[1])
  File "F:\SwitchHacking\switch-usb-mounter\mount.py", line 159, in main
    FUSE(SwitchUSB(), mountpoint, nothreads=True, foreground=True)
  File "F:\SwitchHacking\switch-usb-mounter\fuse.py", line 713, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

Windows 10 Pro x64
Python 3.7.0
pyusb 1.0.2, libusb 1.0, winfsp 1.3.18160

Of course there is some other error underneath this but it errors telling me the error ¯\\\_(ツ)_/¯
Everything works fine in Ubuntu.

**Comment by jakibaki** [comment]
Uhm, that's weird. It was working perfectly for me when I tested it on windows.

**Comment by diman82** [comment]
@noahc3 Run your app with debug mode (run this code before FUSE mount):

```
import logging
logging.basicConfig(level=logging.DEBUG)
```
